version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: money_tracker_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REMEMBER_ME_KEY: ${REMEMBER_ME_KEY}

      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_SMTP_AUTH: "false"
      MAIL_SMTP_STARTTLS: "false"
    depends_on:
      - db
      - mailpit

  db:
    image: mysql:8.0
    container_name: money_tracker_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: money_tracker_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
